//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenWCF.ConsoleApp.GreenServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GreenServiceProxy.IGreenService")]
    public interface IGreenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreenService/Get", ReplyAction="http://tempuri.org/IGreenService/GetResponse")]
        string Get(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreenService/Get", ReplyAction="http://tempuri.org/IGreenService/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGreenServiceChannel : GreenWCF.ConsoleApp.GreenServiceProxy.IGreenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GreenServiceClient : System.ServiceModel.ClientBase<GreenWCF.ConsoleApp.GreenServiceProxy.IGreenService>, GreenWCF.ConsoleApp.GreenServiceProxy.IGreenService {
        
        public GreenServiceClient() {
        }
        
        public GreenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GreenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get(int value) {
            return base.Channel.Get(value);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(int value) {
            return base.Channel.GetAsync(value);
        }
    }
}
